language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t ghblg/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true ghblg/docker-react npm run test
  